"""empty message

Revision ID: c39a0d3956c4
Revises: 
Create Date: 2023-01-15 00:43:26.868059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39a0d3956c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('common_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('scientific_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('native_habitat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fun_fact', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.drop_column('fun_fact')
        batch_op.drop_column('native_habitat')
        batch_op.drop_column('scientific_name')
        batch_op.drop_column('common_name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
